<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_subject</name>
   <tag></tag>
   <elementGuidId>dafc6157-3102-40ac-99b4-bcae48a866f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='react-select-2-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3dec629-cdb5-4f1a-9a16-f0828e7a3eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subjects-auto-complete__option subjects-auto-complete__option--is-focused css-1n7v3ny-option</value>
      <webElementGuid>e786b911-f8e3-488f-9f49-f44b4f609160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-0</value>
      <webElementGuid>76802d34-413b-41e7-beaa-65cf4188d121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>5efbe254-a92d-4e5c-aaef-072cdcaf5a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maths</value>
      <webElementGuid>f1a6b906-e209-46f1-ac45-aea8231c9e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-0&quot;)</value>
      <webElementGuid>d8cef131-75fc-4ecb-9fc1-25466c42ae78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='react-select-2-option-0']</value>
      <webElementGuid>0bf581d8-4362-4943-89cb-1b3a2de083ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subjectsContainer']/div[2]/div/div</value>
      <webElementGuid>b6a6f94c-ada3-4574-b79c-c66860d3364b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ma'])[1]/following::div[4]</value>
      <webElementGuid>6cac330d-4fab-4f26-933b-c23f6400e96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subjects'])[1]/following::div[11]</value>
      <webElementGuid>7f3367b2-2b67-40f0-a27a-981bef69a136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hobbies'])[1]/preceding::div[1]</value>
      <webElementGuid>512c0874-489f-48ab-9eb0-5af4a8d6cc7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sports'])[1]/preceding::div[2]</value>
      <webElementGuid>cd502dd0-95d2-4591-91f4-c6549b1e64aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Maths']/parent::*</value>
      <webElementGuid>448db9c9-e100-48b5-b86f-34cd9fe2ccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div</value>
      <webElementGuid>5f213653-c384-487c-810d-0a056df2e629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'react-select-2-option-0' and (text() = 'Maths' or . = 'Maths')]</value>
      <webElementGuid>92da32db-b274-4208-89a7-7033107acf5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
